# MongoDB development configuration
security:
  authorization: enabled

storage:
  wiredTiger:
    engineConfig:
      cacheSizeGB: 0.25 # Save RAM on dev machine

systemLog:
  verbosity: 0
  quiet: true

net:
  port: 27017
  bindIpAll: true

operationProfiling:
  mode: off
